### ISSUE TITLE
Cant run application after leaf cli install because of case sensitivity

### ISSUE THREAD

**Issue by lyssar** [leafsphp/cli#2]
Hi,
I tested the leaf cli v2.0.4 and used the `create` command:  `leaf create test --api --v3`
First thing i found: Documentation is not correct. `leaf app:serve` doesnt work anymore, it should be `leaf serve`.

The actual error after starting occurs when I try to reach the application:

```bash
> leaf serve
Leaf development server started: http://localhost:5500
Happy coding!
[Thu Feb  3 09:19:43 2022] PHP 8.0.15 Development Server (http://localhost:5500) started
Leaf development server started: http://localhost:5500
Happy coding!
[Thu Feb  3 09:19:46 2022] 127.0.0.1:33078 Accepted
[Thu Feb  3 09:19:46 2022] PHP Warning:  require(/home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/../../../../Config/app.php): Failed to open stream: No such file or directory in /home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/config.php on line 10
[Thu Feb  3 09:19:46 2022] PHP Fatal error:  Uncaught Error: Failed opening required '/home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/../../../../Config/app.php' (include_path='.:/usr/share/php') in /home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/config.php:10
Stack trace:
#0 /home/shens/workspaces/lyssar/applications/test/public/index.php(61): AppConfig()
#1 /home/shens/workspaces/lyssar/applications/test/index.php(24): require_once('...')
#2 {main}
  thrown in /home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/config.php on line 10
[Thu Feb  3 09:19:46 2022] 127.0.0.1:33078 [500]: GET / - Uncaught Error: Failed opening required '/home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/../../../../Config/app.php' (include_path='.:/usr/share/php') in /home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/config.php:10
Stack trace:
#0 /home/shens/workspaces/lyssar/applications/test/public/index.php(61): AppConfig()
#1 /home/shens/workspaces/lyssar/applications/test/index.php(24): require_once('...')
#2 {main}
  thrown in /home/shens/workspaces/lyssar/applications/test/vendor/leafs/mvc-core/src/config.php on line 10
Leaf development server started: http://localhost:5500
Happy coding!
```

> Folder structure
```bash
> ls -al
insgesamt 212
drwxrwxr-x  9 shens shens   4096 Feb  3 09:17 .
drwxrwxr-x  9 shens shens   4096 Feb  3 09:17 ..
drwxrwxr-x  9 shens shens   4096 Dez 16 10:00 app
-rw-rw-r--  1 shens shens   2123 Dez 16 10:00 composer.json
-rw-rw-r--  1 shens shens 142245 Feb  3 09:17 composer.lock
drwxrwxr-x  2 shens shens   4096 Dez 16 10:00 config
-rw-rw-r--  1 shens shens    220 Dez 16 10:00 .editorconfig
-rw-rw-r--  1 shens shens    624 Feb  3 09:17 .env
-rw-rw-r--  1 shens shens    624 Dez 16 10:00 .env.example
drwxrwxr-x  2 shens shens   4096 Dez 16 10:00 .github
-rw-rw-r--  1 shens shens     66 Dez 16 10:00 .gitignore
-rw-rw-r--  1 shens shens    593 Dez 16 10:00 .htaccess
-rw-rw-r--  1 shens shens    672 Dez 16 10:00 index.php
-rw-rw-r--  1 shens shens   2513 Dez 16 10:00 leaf
drwxrwxr-x  2 shens shens   4096 Dez 16 10:00 lib
drwxrwxr-x  2 shens shens   4096 Dez 16 10:00 public
-rw-rw-r--  1 shens shens    295 Dez 16 10:00 README.MD
drwxrwxr-x  5 shens shens   4096 Dez 16 10:00 storage
drwxrwxr-x 17 shens shens   4096 Feb  3 09:17 vendor
```

as you can see: All folders are created lowercase, the application tries to find CamelCase folder names instead.

**Comment by mychidarko** [comment]
Hi @lyssar, I'm now seeing this issue. Is this scaffold leaf MVC or leaf api?

**Comment by lyssar** [comment]
tried it with Leaf API

**Comment by mychidarko** [comment]
Pls try running `leaf install mvc-core`

**Comment by lyssar** [comment]
@mychidarko dunno why you closed the ticket but with `leaf install mvc-core` after `leaf create test --api --v3` the issue is not solved. Still the same issue

**Comment by mychidarko** [comment]
Hi @lyssar, sorry about that

**Comment by mychidarko** [comment]
Try installing the dev version of MVC core.

`composer require leafs/mvc-core dev-main`

**Comment by lyssar** [comment]
New error message, now reported from the frontend:
```php
/home/shens/workspaces/lyssar/applications/leaftest/public/index.php
 
/*
|--------------------------------------------------------------------------
| Additional Leaf Database Config
|--------------------------------------------------------------------------
|
| Load leaf database configuration
|
*/
Leaf\Database::config(DatabaseConfig());
 
/*
|--------------------------------------------------------------------------
| Route Config
|--------------------------------------------------------------------------
|
| Require app routes.
|
*/
require dirname(__DIR__) . '/App/Routes/index.php';
 
/*
|--------------------------------------------------------------------------
| Run Leaf Application
|--------------------------------------------------------------------------
|
| Require app routes
|
*/
app()->run();
 
Arguments
"require(/home/shens/workspaces/lyssar/applications/leaftest/App/Routes/index.php): Failed to open stream: No such file or directory"

```

**Comment by mychidarko** [comment]
It's been fixed. Pls run `leaf create test --api --v3` again

**Comment by lyssar** [comment]
Thanks alot! Works now.
Little thing: the information output after install says:

```bash
You can start with:

  cd leaftest
  leaf app:serve
```

It should be:

```bash
You can start with:

  cd leaftest
  leaf serve
```

since `app:server` doesn't exist anymore

**Comment by mychidarko** [comment]
Thanks a lot 😊

**Comment by mychidarko** [comment]
A new version of leaf cli is available, you can run `leaf update` to install that. It should fix the wrong labelling.
